//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGX.Lean.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaseModule()
        {
            this.UserRight = new HashSet<UserRight>();
            this.UserRoleRight = new HashSet<UserRoleRight>();
        }
    
        public long ID { get; set; }
        public string ModuleCode { get; set; }
        public string ModuleName { get; set; }
        public string ModuleUrl { get; set; }
        public long ParentID { get; set; }
        public string ImgUrl { get; set; }
        public string Icon { get; set; }
        public bool IsBack { get; set; }
        public bool IsMenu { get; set; }
        public bool Valid { get; set; }
        public int ModuleOrder { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateUserID { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public long ModifyUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRight> UserRight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleRight> UserRoleRight { get; set; }
    }
}
