//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGX.Lean.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonComment
    {
        public long ID { get; set; }
        public string ModuleCode { get; set; }
        public System.DateTime DiscussDate { get; set; }
        public string DiscussContent { get; set; }
        public long DiscussUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateUserID { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public long ModifyUserID { get; set; }
        public int DiscussType { get; set; }
        public string DiscussFileUrl { get; set; }
        public string DiscussOfficeFileUrl { get; set; }
        public string DiscussTitle { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
