//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGX.Lean.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.Comment = new HashSet<Comment>();
            this.CommonComment = new HashSet<CommonComment>();
            this.ManagerComment = new HashSet<ManagerComment>();
            this.UserRight = new HashSet<UserRight>();
        }
    
        public long ID { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserGender { get; set; }
        public long RoleID { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public bool IsAdmin { get; set; }
        public int UserType { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateUserID { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public long ModifyUserID { get; set; }
        public long LevelID { get; set; }
        public string ImageUrl { get; set; }
        public int Age { get; set; }
        public string Telephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommonComment> CommonComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerComment> ManagerComment { get; set; }
        public virtual UserRole UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRight> UserRight { get; set; }
        public virtual LenLevel LenLevel { get; set; }
    }
}
